### ISSUE TITLE
preprocessor agnostic gutter configuration

### ISSUE THREAD

**Issue by timoxley** [kristoferjoseph/flexboxgrid#101]
currently can't see a good way to use npm install to install flexboxgrid if you *also* need to adjust the gutters.

Kind of sucks there's not really a good way to expose user-configurable variables for style components, even with preprocessors. Not sure a good pre/post processor-agnostic solution other than exposing a css generator and allowing users to pass in the gutter sizes as variables. Perhaps a cli app?

In my case, I want to remove the gutter completely because the gutter makes certain styles impossible, so perhaps the simplest thing that would work would be special-casing zero gutters (due to aforementioned restriction) and including a zero gutters version in the distribution.

**Comment by kristoferjoseph** [comment]
@timoxley Have been working on a solution for this. Got a little hung up by sass compilers not playing nice with each other. Will keep this issue open and comment as I release solutions.
Thanks!

**Comment by stereokai** [comment]
Subscribed.

**Comment by kristoferjoseph** [comment]
@timoxley How do you feel about a `.gutters` class added to the caontainer being needed to get gutters? The default being no gutters.

**Comment by stereokai** [comment]
Why not use the sass `!default` modifier?

**Comment by timoxley** [comment]
@kristoferjoseph That's pretty neat. I like it.

**Comment by timoxley** [comment]
@stereokai I'm not using sass.

**Comment by kristoferjoseph** [comment]
I will be adding the `.gutters` class in the next release. I am dropping 7.0 because Chrome is shipping custom properties. That is two thirds of evergreen browser!

**Comment by kristoferjoseph** [comment]
At this point you can [use the source css](https://github.com/kristoferjoseph/flexboxgrid/blob/master/src/css/flexboxgrid.css) in [most browsers](http://caniuse.com/#feat=css-variables) and adjust the custom properties to adjust the gutters to your hearts content. _gutters class is still getting added to the next update_
