### ISSUE TITLE
bower dist/flexboxgrid.css missing column support

### ISSUE THREAD

**Issue by FreakinaBox** [kristoferjoseph/flexboxgrid#104]
there is .row and .col.reverse but no .col?
```css
.col {
    display: flex;
    flex-flow: column;
}
```

**Comment by kristoferjoseph** [comment]
It is meant to be used with the responsive column modifiers per the documentation. `col-1...col-12`

**Comment by FreakinaBox** [comment]
I was referring to flex-flow: column not adding columns to a row container. See code above.

**Comment by kristoferjoseph** [comment]
I saw your code snippet and understand what you are meaning. What I am saying is that the current implementation of columns is very specific to use in this grid. What you describe there is more of a general purpose column class. I had one of those previously, but it wasn't needed for anything I was trying to do in this grid. Possibly I missed something. Can you describe the use case that the current grid can't achieve that this addition would fix?

Thanks!

**Comment by RahavLussato** [comment]
:+1: 

i think you should add something like that :

```javascript
.col {
  box-sizing: border-box;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-flex: 0;
  -webkit-flex: 0 1 auto;
  -ms-flex: 0 1 auto;
  flex: 0 1 auto;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -0.5rem;
  margin-left: -0.5rem;
}
```

it will be useful for cases you want to implement column direction, for example if i want to write two labels vertically inside div that nested inside row.

right now you don't have any implementation to flex-direction: column thats part of the
CSS Flexible Box Layout Module.

i use your package and very love it, will really appreciate if you'll add that.

**Comment by blckshrk** [comment]
I agree, I also need that kind of option for a mobile layout with fixed height.

Would be awesome to have a `.column` class with inside a `.row-xs-12` for example.
