### ISSUE TITLE
ie 8 and 9 not support flexboxgrid

### ISSUE THREAD

**Issue by minamorsali** [kristoferjoseph/flexboxgrid#106]
hello , and many thanks for this useful grid system.
Unfortunately ie 8 and 9 not support flexgrid , how can we use flexgrid on ie8 and 9? can we use respond.js like bootstrap for fixing this issue and how?

**Comment by heyallan** [comment]
Actually I would like to see a comparative table of browser support this grid
@minamorsali  `respond.js` address a different issue, I guess.

**Comment by raygesualdo** [comment]
Browser support for flexbox can be viewed here: http://caniuse.com/#feat=flexbox

IE8 and IE9 support for flexbox would require a polyfill (which are generally very slow) or to have your CSS gracefully degrade, perhaps using Modernizr for a feature check.

**Comment by kristoferjoseph** [comment]
@minamorsali yup, old IE does not support flexbox. Check out https://github.com/kristoferjoseph/flextable for some ideas, but in reality, you should use something else for outdated IE... like a bullet.
![smash](https://cloud.githubusercontent.com/assets/76308/9263782/ec4bd25c-41d4-11e5-9f79-62f22136c25f.gif)

**Comment by Aybee** [comment]
You should not give CSS to IE8/9 at all.
