### ISSUE TITLE
Not working in newest Safari Mac

### ISSUE THREAD

**Issue by maximaldesign** [kristoferjoseph/flexboxgrid#109]
The flex box does not work in the newest Safari for Mac (8.0.7)

**Comment by Nirazul** [comment]
What version?
What preprocessor?
What features of the grid did you use?
What features of the grid do not work?
How's the markup?
Do you have additional CSS?
Do you have additional CSS processor steps (e.g. autoprefixer)?
Can you provide a stripped down example of your usage?

**Comment by kristoferjoseph** [comment]
Can you please describe "does not work"?
I have tested it on safari extensively and have not seen any issues.
What am I missing?

Thanks

**Comment by hung-phan** [comment]
I also have that problem. I use version 6.2.0, no preprocessor (only use css loader by webpack). I use row and col-xs-12 feature. But my layout is completely broken.

![screen shot 2015-08-25 at 10 49 17 am](https://cloud.githubusercontent.com/assets/3093244/9474699/0ecc5d6a-4b17-11e5-88ad-afea01129af6.png)
![screen shot 2015-08-25 at 10 49 33 am](https://cloud.githubusercontent.com/assets/3093244/9474700/0ecd9fc2-4b17-11e5-8dce-6ecae23b1191.png)

**Comment by hung-phan** [comment]
import 'normalize.css';
import 'flexboxgrid';

**Comment by hung-phan** [comment]
Work with 6.1.1

**Comment by kristoferjoseph** [comment]
Interesting. This seems to be a difference in how `max-width` is being handled. I'll look into it.

**Comment by visualcookie** [comment]
Discovered the same for Safari on any iOS device.

**Comment by tarkanlar** [comment]
I get the same error on iOS device on both chrome and safari

**Comment by tarkanlar** [comment]
This maybe related https://css-tricks.com/forums/topic/flexbox-not-working-on-safari/

**Comment by marcellefter** [comment]
/* display */
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; 
    /* flex wrap */
    -webkit-flex-wrap: wrap;
        -ms-flex-wrap: wrap;
            flex-wrap: wrap;
    /* flex direction */
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -webkit-flex-direction: row;
        -ms-flex-direction: row;
            flex-direction: row;
    /* justify content */
    -webkit-box-pack: end;
    -webkit-justify-content: flex-end;
        -ms-flex-pack: end;
            justify-content: flex-end;
    /* align items */
    -webkit-box-align: center;
    -webkit-align-items: center;
        -ms-flex-align: center;
            align-items: center;
    /* align contents */
    -webkit-align-content: space-between;
        -ms-flex-line-pack: justify;
            align-content: space-between;

**Comment by visualcookie** [comment]
@marcellefter What does it mean? Does this fix it? Where to put it?

**Comment by kristoferjoseph** [comment]
Does flexboxgrid.com look correct on the same setup? Can you screenshot it if it doesn't? I am not seeing any issues so I need more info to be able to help. Thank you.

**Comment by marcellefter** [comment]
@visualcookie for to work in Safari, display must have -webkit-box and other which I wrote.

**Comment by Nirazul** [comment]
@marcellefter 
The old `-webkit-box` syntax is deprecated in Safari since v7:
http://caniuse.com/#search=flexbox

**Comment by kristoferjoseph** [comment]
OK problem solved. I updated the grunt plugin and now it is adding the updated prefixes you need for bleeding edge Safari. I will push the update tonight.

**Comment by hung-phan** [comment]
:+1:

**Comment by marcellefter** [comment]
Complete prefixes - http://joxi.ru/gmvqOKRsO8KQra

**Comment by visualcookie** [comment]
:+1:

**Comment by manuelmazzuola** [comment]
:+1:
