### ISSUE TITLE
False-positive on Wappalyzer

### ISSUE THREAD

**Issue by brunowego** [kristoferjoseph/flexboxgrid#112]
Wappalyzer detects Flexbox Grid as Bootstrap https://github.com/AliasIO/Wappalyzer/issues/847.

This happens because of column names: https://github.com/AliasIO/Wappalyzer/blob/920d3f6465824aa63633103654b22e4d9fd9ad37/src/apps.json#L5847-L5859

**Comment by jchck** [comment]
The benefit to using same column names as Bootstrap is ability to switch Bootstraps grid out with Flexboxgrid.

Is Wappalyzer not correctly FBG detecting FBG important?

**Comment by brunowego** [comment]
Not have FBG detection in Wappalyzer.

**Comment by jchck** [comment]
Right I understand Wappalyzer detection isn't happening, is that important and if so, why?

**Comment by kristoferjoseph** [comment]
Not overly concerned with Wappalyzer detection. Seems like a faulty way to determine what css framework you are using anyhow, since a lot of grids use this convention.
