### ISSUE TITLE
index.css and index.min.css have the same layout ?

### ISSUE THREAD

**Issue by KeyEzaite** [kristoferjoseph/flexboxgrid#115]
I open two files in folder flexboxgrid-6.2.0\css and see index.css and index.min.css have the same layout. They have no indent, no spaces in code.

**Comment by kristoferjoseph** [comment]
Are you saying that you are not seeing an unminified version of index.css?
Index is for the demo site. I am moving that to it's own gh-pages branch. Sorry for the confusion.
