### ISSUE TITLE
The .container's width is too large

### ISSUE THREAD

**Issue by ckuijjer** [kristoferjoseph/flexboxgrid#123]
The `.container` variant of flexboxgrid has some issues regarding its width:

1. If you make the screen smaller, you'll notice a horizontal scrollbar appearing
2. At the exact breakpoints (e.g. 1200px) the `.container-fluid` and `.container` aren't aligned, the `.container` doesn't have the `--outer-margin`

See http://codepen.io/ckuijjer/pen/xwENJv for this issue.

**Comment by ckuijjer** [comment]
To see the behaviour of the pull request please take a look at http://codepen.io/ckuijjer/pen/ojzOqa

**Comment by VinSpee** [comment]
:+1: thanks!

**Comment by jaunesarmiento** [comment]
+1

**Comment by jaunesarmiento** [comment]
Looks like using `.wrap` along with `.container` fixes this issue. Maybe document the usage of `.wrap`?

**Comment by ckuijjer** [comment]
I'm not entirely sure if it does, I've updated my http://codepen.io/ckuijjer/pen/xwENJv to add one example with both `.container` and `.wrap`.

**Comment by jaunesarmiento** [comment]
You're right @ckuijjer, I was looking at the developer console when I'm viewing Flexbox Grid example. I thought it worked on my example.

It seems a quick solution to this is similar to the example, by creating a `.wrap`:

```
.wrap {
  max-width: 1200px;
  margin: 0 auto;
}
```

And using it with `.container-fluid`.

**Comment by darkbasic** [comment]
I use container-fluid with max-width because in its current state container is not usable :(

**Comment by ArnaudValensi** [comment]
I have the same issue.

**Comment by jdickan** [comment]
Adding this to my custom CSS seemed to fix the behavior, while allowing for use of the .container class.

.container {
	max-width: 1200px;
	margin: 0 auto;
	margin-right: auto;
 	margin-left: auto;
 	padding-right: 2rem;
 	padding-left: 2rem;
}
