### ISSUE TITLE
links with images inside overflowing grid column

### ISSUE THREAD

**Issue by leandroruel** [kristoferjoseph/flexboxgrid#129]
when you have an <a> tag with a <img> inside, the image not scale inside the grid column, and this overflow out of the grid column. sorry for my bad english

**Comment by Aybee** [comment]
Please post a Link to a gist codepen http://codepen.io/, jsfiddle http://jsfiddle.net/ or similar.

Maybe its done with a max-width:100%; to your IMG after you display your IMG as block.

**Comment by kristoferjoseph** [comment]
You need to add `img { max-width: 100% }` for responsive images.
