### ISSUE TITLE
How to have boxes of equal height inside a row

### ISSUE THREAD

**Issue by Kerruba** [kristoferjoseph/flexboxgrid#132]
Hi,

I would like to have equal size blocks inside of a container (row), how is it possible with flexboxgrid?
Should be achievable using the syntax align-items: stretch on the container

**Comment by Aybee** [comment]
Inside a row you already have "boxes", whatever this might be, of equal height - the .col-... elements.

If you  want to stretch the block elements **inside** the cols vertically you have to give them 100% height.

In online demo this will be e.g.
```css
[class^="box-"] {
  height: 100%;
}
```

**Comment by kristoferjoseph** [comment]
You can add an override for stretch. I will add a feature request issue with the stretch option.

**Comment by cg433n** [comment]
@kristoferjoseph How do you add an override for stretch?

**Comment by jimmyadaro** [comment]
This is what worked for me:

```
.your-container > .row {
  align-items: stretch !important;
}
```

**Comment by elalemanyo** [comment]
@Aybee Sorry but `height: 100%;` make for me no difference, can you make one example?
Thanks!

**Comment by Aybee** [comment]
On this page https://flexboxgrid.com/ run following JavaScript with your devtools
```js
var boxes = document.querySelectorAll(".box-row");

boxes.forEach(function(box) {
  box.style.backgroundColor = 'tomato';
  box.setAttribute('contenteditable', true);
});
````
Now click into the tomato boxes and insert some text.

Now use CSS from above with devtools.

**Comment by elalemanyo** [comment]
@Aybee It works! [Here is a simple example](https://codepen.io/elalemanyo/pen/EMMvEN).

Thanks!

**Comment by Aybee** [comment]
Yes I know. You're welcome.
