### ISSUE TITLE
Feature request: Hide/Show content

### ISSUE THREAD

**Issue by boustanihani** [kristoferjoseph/flexboxgrid#138]
Could you please add the ability to hide/show content based on xs, sm, md & lg

**Comment by DerFlatulator** [comment]
+1, came here to ask exactly that. Something like:


`hide-xs-down` - Hide on xs and xxs.
`hide-md-up` - Hide on md and lg.
`hide-xs-only` - Hide on xs only.
...

And counterparts:

`show-md-only` - Only show on md.
`show-md-up` - Only show on md, lg.
...

I think just `{ display: none; }` should do the trick.

**Comment by CezarLuiz0** [comment]
+1

**Comment by kristoferjoseph** [comment]
I will not be adding this to flexbox grid.

**Comment by kristoferjoseph** [comment]
https://www.dropbox.com/s/tooi54wv6nxvbak/Screenshot%202016-01-28%2011.26.39.png?dl=0

**Comment by istiti** [comment]
@kristoferjoseph  design anti-pattern? it's relative. it used on bootstrap and everywhere, very easy to use. if this lib implement hide-*  it will realy be interesting, you really don't want approach this request ? :D
