### ISSUE TITLE
Optimal number of decimal places

### ISSUE THREAD

**Issue by lsorber** [kristoferjoseph/flexboxgrid#149]
According to [1], IE7-11 will truncate percentages to 2 decimal places. Flexbox grid specifies percentages up to 3 decimal places. This means IE will interpret a percentage like `66.667%` as `66.66%`, where it should have really been `66.67%`. A solution is to specify pre-rounded percentages up to 2 decimal places for IE prefixed properties.

Not super important, since rounding `66.66%` and `66.67%` of a 4K screen result in the same number of pixels, but still :-). This will only start mattering once we have 8K screens.

[1] http://cruft.io/posts/percentage-calculations-in-ie/

**Comment by kristoferjoseph** [comment]
Ugh, IE still causing problems ;) 
From my understanding webkit based browsers round to 3 points, hence the current decimals.
I can do some experimenting to see if it causes any major issues to round to two.

**Comment by kristoferjoseph** [comment]
please test with 6.3.1
