### ISSUE TITLE
Ongoing SASS support

### ISSUE THREAD

**Issue by zslabs** [kristoferjoseph/flexboxgrid#151]
Hey,
Wanted to start off saying thanks for making this! Is ongoing SASS support planned for future versions? Thanks!

**Comment by kristoferjoseph** [comment]
Unfortunately the answer is no for the time being. There were WAY too many issues trying to support all of the things SASSY folk were trying to do ( different compilers, different build tools etc. ).
 
Going forward flexboxgrid will be a `.css` file that you can include. By default it will be 12 columns and have the same media queries as bootstrap. 

I will have a build system in place that will allow you to customize the output, but I will only be supporting the included build system nothing else.

I gave it a very serious go and got a number of impossible issues filed right away. I need this project to be stable and maintainable for everyone's sanity.

Hope I didn't ruin your day :/

**Comment by zslabs** [comment]
Ha no worries ;) appreciate the creation of the project nonetheless. I ended up taking it and spinning up my own grid system for my needs - I'll contribute back once it's done to see if you agree with the optimizations I've made (non-SCSS of course).
