### ISSUE TITLE
Your CDN doesn't work

### ISSUE THREAD

**Issue by yanisurbis** [kristoferjoseph/flexboxgrid#153]
https://gyazo.com/8d655d8d7975fd7e56b2fc99fa8fa384

**Comment by Volzy** [comment]
You didn't implement the CDN-file as http:// or https://, so it's looking for the file on your locale machine (file://). That's why it's not working for you. Nothing wrong with CDN.

@yanisurbis

**Comment by yanisurbis** [comment]
Thank you and sorry =)
