### ISSUE TITLE
Adjusting the breakpoints

### ISSUE THREAD

**Issue by prewk** [kristoferjoseph/flexboxgrid#154]
I feel this is a really dumb basic CSS question but.. how can I adjust the breakpoints?

I assumed I could somehow use `font-size` on `body` or something, given that the breakpoints are in `em`, but I can't get it do do anything.

The out-of-the-box `xs` breakpoint ends up at 1023px atm.

Thanks!

**Comment by kristoferjoseph** [comment]
You can change the breakpoint size variables and run the build locally.
https://github.com/kristoferjoseph/flexboxgrid/blob/master/src/css/flexboxgrid.css#L19

**Comment by prewk** [comment]
Ah, I went that route but thought it was overkill. Thanks.
