### ISSUE TITLE
#125 not included when installing via NPM.

### ISSUE THREAD

**Issue by bschnelle** [kristoferjoseph/flexboxgrid#155]
I get 6.3.0 when installing via NPM, but PR #125 doesn't appear to be included in the installed package despite being part of the the master branch.  Loving the library otherwise!

**Comment by bschnelle** [comment]
Any thoughts on this?

**Comment by kristoferjoseph** [comment]
I haven't had time to test all of the new merges yet so I haven't deployed.

**Comment by kristoferjoseph** [comment]
Published 6.3.1 :)
