### ISSUE TITLE
Erroneous Example on Homepage?

### ISSUE THREAD

**Issue by dk0r** [kristoferjoseph/flexboxgrid#156]
**Issue**: The 'Nested Grids' example on the homepage has too many `</div>`'s in it.
**Solution**: Remove one `</div>` from the Nested Grids example so that it looks like this:
> https://gist.github.com/dk0r/91afebe22e32ea4d7472

**Screenshot**: http://i.imgur.com/I1gHjXu.png

**Comment by paxperscientiam** [comment]
From what I can tell, the nesting example does not work at all. However, the source code -- which  has a class references to 'box-container' and 'box-nested' -- does recreate the nesting effect; however, this these classes are defined in the accompanying "style.css" style sheet.

The markup example only produces two side-by-side auto-flexed columns. Can nesting be done with the flexgrid "library" or is external styling required?

**Comment by kristoferjoseph** [comment]
Thanks for pointing this out. It is fixed in the current code, just not deployed to the home page yet.
