### ISSUE TITLE
Responsive utilities

### ISSUE THREAD

**Issue by listepo** [kristoferjoseph/flexboxgrid#157]
@kristoferjoseph what do you think about http://getbootstrap.com/css/#responsive-utilities in 7.0?

**Comment by wannymiarelli** [comment]
+1

**Comment by PeterPanen** [comment]
+1

**Comment by bitdivision** [comment]
Author won't add this. See https://github.com/kristoferjoseph/flexboxgrid/pull/140 and https://github.com/kristoferjoseph/flexboxgrid/issues/138

**Comment by kristoferjoseph** [comment]
hmmmmmmm should I encourage an anti-pattern is more of the question here? Does this have enough to do with a grid to make it a key feature or does this belong as a separate utility so as not to distract from the intent of this project which is flexbox layout?

**Comment by listepo** [comment]
I think like flexboxgrid-utilities

**Comment by kristoferjoseph** [comment]
*Deal*, I'll make some utility add ons then!
Thank you for the feedback! ✨ 💖 ✨

**Comment by rcherem** [comment]
I have been extending it with this:

.visible-xs,
.visible-sm,
.visible-md,
.visible-lg { display: none !important; }

@media (max-width: 48rem) {
	.visible-xs      { display: block !important;      }
	.row.visible-xs  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important;        }
	table.visible-xs { display: table !important;      }
	tr.visible-xs    { display: table-row !important;  }
	th.visible-xs,
	td.visible-xs    { display: table-cell !important; }
}
@media (min-width: 48rem) and (max-width: 62rem) {
	.visible-sm      { display: block !important;      }
	.row.visible-sm  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important;        }
	table.visible-sm { display: table !important;      }
	tr.visible-sm    { display: table-row !important;  }
	th.visible-sm,
	td.visible-sm    { display: table-cell !important; }
}
@media (min-width: 62rem) and (max-width: 75rem) {
	.visible-md      { display: block !important;      }
	.row.visible-md  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important;        }
	table.visible-md { display: table !important;      }
	tr.visible-md    { display: table-row !important;  }
	th.visible-md,
	td.visible-md    { display: table-cell !important; }
}
@media (min-width: 75rem) {
	.visible-lg      { display: block !important;      }
	.row.visible-lg  { display: flex !important;
					   display: -webkit-flex !important;
					   display: -ms-flexbox !important;
					   display: -webkit-box !important;
					   display: flex!important;        }
	table.visible-lg { display: table !important;      }
	tr.visible-lg    { display: table-row !important;  }
	th.visible-lg,
	td.visible-lg    { display: table-cell !important; }
}
@media (max-width: 48rem)                        { .hidden-xs { display: none !important; } }
@media (min-width: 48rem) and (max-width: 62rem) { .hidden-sm { display: none !important; } }
@media (min-width: 62rem) and (max-width: 75rem) { .hidden-md { display: none !important; } }
@media (min-width: 75rem)                        { .hidden-lg { display: none !important; } }

**Comment by stunaz** [comment]
Also
have a look at https://material.angularjs.org/latest/layout/introduction and his options.
Really great utilities

**Comment by littleguga** [comment]
@listepo, @wannymiarelli, @PeterPanen, @bitdivision i couldn't wait, so i created a tiny npm package for this:

https://github.com/littleguga/flexboxgrid-helpers
https://www.npmjs.com/package/flexboxgrid-helpers

Hope it will be useful!

**Comment by kristoferjoseph** [comment]
☝️ Yo, errbody give this a whirl and see if it works for you. If so I will close this issue. thx

**Comment by PolGuixe** [comment]
I have created a PR: https://github.com/kristoferjoseph/flexboxgrid/pull/211  which adds hidden columns. 

@kristoferjoseph what do you think?
