### ISSUE TITLE
Could this be made to support the flexbox model of React Native?

### ISSUE THREAD

**Issue by kristianmandrup** [kristoferjoseph/flexboxgrid#164]
Just wondering... Would be SO awesome!

https://facebook.github.io/react-native/docs/flexbox.html

**Comment by kristoferjoseph** [comment]
Seems like a great idea. How would you go about doing this?
Do you have a demo project that I could experiment on?

**Comment by kristoferjoseph** [comment]
Closing. React Native is a new eco-system that, while interesting, is not the target for this project. Would be interested to see someone work on a fork and make a PR if they like the outcome.
