### ISSUE TITLE
Flexbox-basis problem with Safari

### ISSUE THREAD

**Issue by thierryskoda** [kristoferjoseph/flexboxgrid#168]
Hi,

I have a problem when I'm using flexboxgrid with safari. Here is the code that I have

```
<div class="container">
        <div class="row">
          <div class="col-sm-3">
             <h1>test</h1>
          </div>
          <div class="col-sm-8 col-sm-offset-1">
             <h1>test</h1>
          </div>
       </div>
</div>
```

So the total of the row is 12 columns but when I test it in safari, the 'div' that contains 'col-sm-8...' appears on the other line. When I use the console to see what is the error, I tried to change the 'flex-basis' to 66.58% instead of 66.667% and it seems to work. 

Anyone ever had the same issue and knows how to fix it? 

Thank you!

**Comment by thierryskoda** [comment]
ahhh I think it's because I had bootstrap at the same time and I have some properties that were overlapping

**Comment by kristoferjoseph** [comment]
Ah sorry see #170
