### ISSUE TITLE
Can I add this lib to pub.dartlang.org ?

### ISSUE THREAD

**Issue by adaojunior** [kristoferjoseph/flexboxgrid#172]
My inicial plan is to copy the files inside dist to a brand new a repository, I would point to your docs and warn that PR must be send to your repo.
But if you want I can also help you creating a task in your gulp file to generate the package for pub, and you upgrade it on pub.dartlang.org

**Comment by kristoferjoseph** [comment]
uh, I would rather have a PR than a copy paste if possible?

**Comment by adaojunior** [comment]
@kristoferjoseph sure, that would be even better. I'll send a PR as soon as I have some time Available.
