### ISSUE TITLE
Class .col with flex-direction: column

### ISSUE THREAD

**Issue by oleksiibilous** [kristoferjoseph/flexboxgrid#173]
Hello

I could not find class `.col` with `flex-direction: column;` inside. Maybe I missed something, but there is class`.col.reverse` with `flex-direction: column-reverse` and I thought that class `.col` would be a way to implement default vertical flow.

Can you advise, please?

Thanks

**Comment by kristoferjoseph** [comment]
Great question!
This is was a contentious decision. I fully expected to have `.col` behave the way you explained, but after experimenting with this and discovering the unintended side effects this approach had on the content in the grid I decided to remove this and think about it more.

I encourage you to try it out yourself in dev tools to see what I mean. Then come back and tell me your thoughts. Thanks!

**Comment by DaveRevay2** [comment]
What is the recommended way of doing columns right now?
It is quite surprising that `flex-direction: column` is not featured.

Would love to see an equivalent feature set to some of the other layout systems such as:
https://material.angularjs.org/latest/layout/alignment

**Comment by matheusdavidson** [comment]
this is really needed, ```flex-direction: column``` is part of flexbox.
