### ISSUE TITLE
col-xs-offset-* pollutes other devices sizes, can't be turned off

### ISSUE THREAD

**Issue by jacobp100** [kristoferjoseph/flexboxgrid#175]
`col-xs-offset-*` will affect non-xs screen sizes.

There's not `col-**-offset-0`, so there is no way to offset something just on an xs screen.

**Comment by kristoferjoseph** [comment]
Oh no! OK I have a release coming out and will make sure to add this to that.

**Comment by IljaDaderko** [comment]
+1

**Comment by denkan** [comment]
+1

**Comment by brandensilva** [comment]
+1. 

col-**-offset-0 would be extremely useful so you can target specific offsets on certain breakpoints.

**Comment by zhenbinjing** [comment]
col-**-**  with col-**-offset-**  separate written
For example：
.col-xs, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .col-xs-offset-0, .col-xs-offset-1, .col-xs-offset-10, .col-xs-offset-11, .col-xs-offset-12, .col-xs-offset-2, .col-xs-offset-3, .col-xs-offset-4, .col-xs-offset-5, .col-xs-offset-6, .col-xs-offset-7, .col-xs-offset-8, .col-xs-offset-9 { -webkit-box-flex: 0; -ms-flex: 0 0 auto; flex: 0 0 auto;}
.col-xs, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{ padding-left:2rem; padding-right: 2rem;}

**Comment by t22james** [comment]
am i right in thinking this looks fixed in current code?
https://github.com/kristoferjoseph/flexboxgrid/blob/master/dist/flexboxgrid.css
(considering using this in a project but won't unless this bug is confirmed fixed)

**Comment by ssamuli** [comment]
Yes, seems like 6.3.1 fixes this bug.
