### ISSUE TITLE
Install the SASS lib NPM

### ISSUE THREAD

**Issue by eamaral92** [kristoferjoseph/flexboxgrid#178]
I need to install the SASS flexboxgrid via npm, but the README do not have any info about how to do it!

**Comment by kristoferjoseph** [comment]
Am thinking about publishing the SASS version as `flexboxgrid-sass` for ya'll to include.
The reason I stopped working on it though was because people were trying to use it with unsupported SASS compilers and I have no way of making them all work together. :(

**Comment by ccarterc** [comment]
It's fine for you to use whatever css compiler you wish.  Just make sure to distribute the compiled css instead of .scss files.  Very annoying to have to download, install, configure a .scss compiler just to get access to this great project.

**Comment by kristoferjoseph** [comment]
@ccarterc EXACTLY!
You should never have to compile anything unless you want to customize it.

**Comment by samIntegrateur** [comment]
+1 for a scss version to customize breakpoints.
