### ISSUE TITLE
Bug with col-sm-5 col-sm-2 col-sm-5

### ISSUE THREAD

**Issue by AnghelGabriel** [kristoferjoseph/flexboxgrid#181]
Found a bug when using col-sm-5 col-sm-2 col-sm-5

![image](https://cloud.githubusercontent.com/assets/2881307/15826537/8f0ae5d4-2c10-11e6-984c-e730ae52d45e.png)

The content of the page was modified using chrome console, so it will not be visible on the website.

**Comment by kristoferjoseph** [comment]
Please test this with the new version and let me know if it is fixed 6.3.1

**Comment by littleguga** [comment]
@AnghelGabriel @kristoferjoseph i've just tested now it works fine.

**Comment by AnghelGabriel** [comment]
@kristoferjoseph Tested and works fine. 
Thanks.
