### ISSUE TITLE
is there any sass version for flexboxgrid?

### ISSUE THREAD

**Issue by imasood** [kristoferjoseph/flexboxgrid#185]

**Comment by bcallaars** [comment]
I suppose you could just include the css into sass?

**Comment by graemegeorge** [comment]
Really? No sass/less/other versions? Curious of the reasons for that.

**Comment by imasood** [comment]
@bcallaars yeah, it could be done with including css into sass. but it's not good way and i can't have a good control on my app and other things.

**Comment by thomasfrobieter** [comment]
What about this: https://github.com/hugeinc/flexboxgrid-sass

**Comment by imasood** [comment]
it's good repo for sass veriosn and maybe helpful.
thanks
