### ISSUE TITLE
columns as display: flex

### ISSUE THREAD

**Issue by Taakn** [kristoferjoseph/flexboxgrid#188]
Hello,

Right now you have your columns with `display: block`. Wouldn't it more sense to have them as `display: flex` with  `flex-direction: column `?

Thanks

**Comment by kristoferjoseph** [comment]
https://github.com/kristoferjoseph/flexboxgrid/issues/173

**Comment by Taakn** [comment]
ok thanks so much I didn't see this issue. I needed to override mine with `display: flex` because of nested items. Basically I needed to have my last rows stretch or be at the bottom of their parent column.

I haven't seen any issues so far though. Would you mind elaborating on your choice and what made you change your mind?

Thanks again
