### ISSUE TITLE
Rouding error because insuficient digit precision

### ISSUE THREAD

**Issue by moimael** [kristoferjoseph/flexboxgrid#190]
HI,

I have a grid system based on flexboxgrid, where the container is 975px wide. I have 3 columns in this container, each should be 325px. But since flexboxgrid only have a precision of 3 digits after comma, my items are 324.983px wide, leaving a one pixel blank when applying an overlay on it.

Here is the current css applied by flexboxgrid :
```css
flex-basis: 33.333%;
max-width: 33.333%;
```

Changing flex-basis and max-width to have 6 digits precision fix the issue (at least on Firefox, do not seems to have any effect on Chrome probably because of this : [https://bugs.chromium.org/p/chromium/issues/detail?id=447207](https://bugs.chromium.org/p/chromium/issues/detail?id=447207))

Here is the fixed css :
```css
flex-basis: 33.333333%;
max-width: 33.333333%;
```

**Comment by ArKam** [comment]
A solution regarding the precision error could be to use the calc() method introduced with CSS3 in conjunction with the VW and VH metrics.

It will help regarding the precision problem but will bring to flexgrid a cool feature by allowing nearly infinite grid layout, not only a 12 one as for now.

Example:

We assume a 12 column usual layout here.

`
.col-xs {
    margin-left: calc(100vw/12);
}
`

**Comment by kristoferjoseph** [comment]
added to 6.3.1
