### ISSUE TITLE
sass

### ISSUE THREAD

**Issue by furkankinyas** [kristoferjoseph/flexboxgrid#192]
can u add sass file for customize

**Comment by JohanMouchet** [comment]
It seems that there is sass branch here: https://github.com/kristoferjoseph/flexboxgrid/blob/sass/src/sass/flexboxgrid.scss, but I don't know how up to date this is.

**Comment by aolko** [comment]
almost a year ago, quite old

**Comment by kristoferjoseph** [comment]
@aolko there is a bunch of discussion around this topic. I will not be supporting sass.

**Comment by kristoferjoseph** [comment]
https://github.com/kristoferjoseph/flexboxgrid/issues/151
