### ISSUE TITLE
Chrome - 6 col-**-2 overflow 

### ISSUE THREAD

**Issue by rmwdeveloper** [kristoferjoseph/flexboxgrid#194]
Seems to be a problem in chrome only. 

https://jsfiddle.net/uL0qcdkv/3/

![Overflow bug](http://i.imgur.com/D1FWV0t.png)

**Comment by littleguga** [comment]
Confirm. Another demo: http://jsbin.com/hoyatinilu/edit?output

Tested on last Chrome, win7 64x, 1920x1080 monitor.
With 1366 monitor - works fine.

![image](https://cloud.githubusercontent.com/assets/12018713/17275329/7fcc53e2-570c-11e6-9c8f-b4d3d8c7738c.png)

**Comment by littleguga** [comment]
For now you can use this dirty hack:

```
.col-md-2{
  -webkit-flex-basis: 16.66666667% !important;
  -ms-flex-preferred-size: 16.66666667% !important;
  flex-basis: 16.66666667% !important;
  max-width: 16.66666667% !important;
}
```
