### ISSUE TITLE
Why we need 'margin-right: -.5rem;'?

### ISSUE THREAD

**Issue by littleguga** [kristoferjoseph/flexboxgrid#199]
in .row class:

    margin-right: -.5rem;
    margin-left: -.5rem;

it creates horizontal scrollbar in last chrome.

Why we need this code?

**Comment by kristoferjoseph** [comment]
This is for handling when `flex-wrap` kicks in. 
This isn't the reason for scrollbars. The omission of the container is usually the culprit there.
New version removes all of this nonsense though.
