### ISSUE TITLE
Add ability to customize number of columns

### ISSUE THREAD

**Issue by kristoferjoseph** [kristoferjoseph/flexboxgrid#20]
Add variables to define a custom column count.

**Comment by kristoferjoseph** [comment]
Customizable columns will be available when pull request #55 lands. 

Depends on #55

**Comment by dandv** [comment]
> Customizable columns will be available when pull request #55 lands.

PR #55 looks closed?

**Comment by kristoferjoseph** [comment]
Flexbox grid will not be adding preprocessor support. It will remain a 12 column grid. This enables a lot of layouts and nested grids enable any number you need.
