### ISSUE TITLE
Invalid cdn link 

### ISSUE THREAD

**Issue by diedsmiling** [kristoferjoseph/flexboxgrid#207]
Hi!
Cdn link provided in `README.md` to sdelivr.net is invalid. https://cdn.jsdelivr.net/flexboxgrid/6.3.1/flexboxgrid.min.css returns 404 "File not found error". 
<img width="623" alt="screenshot 2016-08-13 16 56 54" src="https://cloud.githubusercontent.com/assets/1911142/17643588/493d2b42-6177-11e6-8beb-b33826826b8c.png">

**Comment by kristoferjoseph** [comment]
Apologies. This is used to happen automagically, but seems to have stopped working. Will get it propagated.

**Comment by kristoferjoseph** [comment]
OK figured it out, jsdelivr changed the way it works. I had to add an `update.json` for it to auto update. Let's see if that works.

**Comment by kristoferjoseph** [comment]
Nope jsdelivr removed. Use CDNJS link.
