### ISSUE TITLE
Confusion about -xs, -sm, -lg, -md

### ISSUE THREAD

**Issue by Shahor** [kristoferjoseph/flexboxgrid#209]
New to grid systems, I find myself quite confused by the conventions used here, especially since they're not explained anywhere.

I believe those stand for sizes, like "**extra small, small, medium, large**".

I fiddled around and the **difference** between those **seem to be in the break points for media queries**, but maybe I'm super wrong and don't understand a thing about it.

Maybe **some basic documentation would be good** to actually explain those since they, **at first glance, don't seem to have any difference at all.** 
**I would gladly write it** if needed, but **if someone could care to explain a little bit** :)

edit: Bolding to make it clearer, not to be a jerk :)

**Comment by kristoferjoseph** [comment]
I hear you. These were suggested because they aligned with what people were used to in Bootstrap. http://getbootstrap.com/css/#grid

I will def add some more documentation around them, but you can read up about them in the meantime to get you unstuck.

:)

**Comment by Shahor** [comment]
Thank you sir o/
