### ISSUE TITLE
How to use flexboxgrid with Bootstrap 3?

### ISSUE THREAD

**Issue by gremo** [kristoferjoseph/flexboxgrid#212]
How to use flexboxgrid with Bootstrap 3? Classes from flexboxgrid (`.col-*`, `.row`, `.container`) will messup classes from Bootstrap, I suppose.

What about providing a default class prefix (i.e. `fg-`) or use LESS/SASS variables?

**Comment by db0sch** [comment]
I guess the aim is to replace the bootstrap grid system.
So I suppose, no compatibility what-so-ever with bootstrap should be expected.
but that's just my opinion.

**Comment by kristoferjoseph** [comment]
Yes @db0sch is correct, it was meant to be used as a drop-in replacement for the boostrap grid. You would need to download a custom build of boostrap without the grid.

**Comment by gremo** [comment]
Well, not exactly. Containers in bootstrap have a default padding while rows have negative margins and both matches. With flexbox grid they differ, I have a few issues with this. I'm using Bootstrap 3 with the grid system disabled (using LESS). Any clue?

**Comment by kristoferjoseph** [comment]
Ah not sure since I am not a bootstrap user. Very interested in hearing
about what you come up with if you find a fix.

**Comment by josephdburdick** [comment]
btw @gremo as of yesterday Bootstrap 3 [will no longer be actively maintained](https://github.com/twbs/bootstrap/issues/20631).
