### ISSUE TITLE
Missing documentation: container and default body font size

### ISSUE THREAD

**Issue by djensen47** [kristoferjoseph/flexboxgrid#213]
First, thanks for this project. It's really great. I'm willing to put in a PR for this if you are open to the following ideas for the docs.

While experimenting with flexboxgrid, I discovered a couple of things that might be nice to have in the documentation.

- [ ]  An explanation and/or example of `container` and `container-fluid`

  If you've used grid systems before, you probably know what it is. But it also means you're looking for it when evaluating which library to use. If you don't know how to use `container`, then a little bit in the docs would be nice.

- [ ] Note that `rem` is used for the media queries.
  - Your body font size will affect the media query breakpoints.
  - Yes, this actually makes things kinda flexible 👍 
  - But, if you don't know that and set you font size to the "wrong" value, you might be "Why is 'medium' breaking at 996px?" 👎 
    - _I'm probably an idiot for experimenting with this with the body font size set to something other than 16px (and I'm not even sure if that's correct) but it happened and the results were weird._
  - Document the expected font-size to achieve the defaults.

- [ ] Note the values for the breakpoints as well: 48rem, 64rem, 75rem. Also how they translate to pixels at 16px (although hopefully most people can multiply 😉).

If you would like, I can make an attempt at this in a PR. Just need confirmation that 16px is the default font-size (I'm 99% sure it is).

**Comment by djensen47** [comment]
Maybe also document a list of forks that use various pre-processors so you stop getting issues about supporting sass or stylus or whatever? Might get un-maintainable quickly though. Just a thought.

**Comment by kristoferjoseph** [comment]
Thanks for the interest. I am very close to releasing 7.0 which does not have a container class any longer. The rem unit is not supported for media queries in some versions of Safari.

**Comment by djensen47** [comment]
Okay, thanks. Also, I just now realized my mistake, I meant `em` not `rem`.

**Comment by kristoferjoseph** [comment]
Understandable, I say `rem` when I mean `em` all the time because `rem` is just so fabulous I wish I never needed `em`.

Also I don't want to burst your bubble, I really do like your enthusiasm and want to encourage contribution. I just had to make some major changes to address common pain points I keep hearing about from users. Wish I had more time to dedicate to getting it out. 

Thanks gain. 

btw, yes the default font size of the browser is 16px so 1 em/rem at the `:root`
