### ISSUE TITLE
Great project, naming convention question

### ISSUE THREAD

**Issue by iautomation** [kristoferjoseph/flexboxgrid#218]
First, thanks for forming this mini code collection. I scoured the web for 1 "framework" that would just simply give a logical grid that is useful for real-world scenarios, and they all failed in one place(or more, much more). This one fit the bill! I'll be donating if my business takes off, or when I'm able, because you sir have saved me time.

Ok with that said, I have 1 small bone to pick with the _sm/lg/[...]_ naming convention, albeit take note that I'm incredibly OCD about things, but it's just a suggestion. I'll use two examples:
`col-xs-6` and `start-xs`
So the logic is as such:
_For [type], when [device-width], do [details]_
So for `col-xs-6` it would be:
_For column, when extra small, do size 6_
**Ok, IMO it would seem more logical to place the if clause at the beginning, then define from there:**
_When [device-width], for [type], do [detail]_
So we'd end up with:
`xs-col-6` and `xs-start`

Best

**Comment by deromanenko** [comment]
At my opinion, it should pronounce like this:
_this is COLUMN, which when shown on EXTRA SMALL, will be SIZE 6_

Current convention make it easier to understand what element you see at the moment

**Comment by iautomation** [comment]
@deromanenko Thanks for your added input. That is true, and I understand how that could be preferrable, but the same reasoning is used for my logic, just on a broader scope. A real-world example would be: _I'm looking at the header menu with all elements on the inside, and want to modify everything under extra small_ I find that to be a more common situation for me than looking for the current element type first, as I am modifying one "responsive scope" at a time.

**Comment by kristoferjoseph** [comment]
Thanks for the feedback! I am not a huge fan of this convention either, but this follows the boostrap convention which is widely used so understood by a large number of people. 
It also makes sense from a css selector standpoint. With selectors you want them to be grouped by block so they read left to right as the same then add modifiers to the end. `.col-xs-1`,`.col-xs-2`, etc.
 `block-element-modifier[s]` Or BEM is kind of responsible for solidifying this approach that a lot of hard core css nerds were using already.
