### ISSUE TITLE
10px gap on right size when using col-xs

### ISSUE THREAD

**Issue by craigcosmo** [kristoferjoseph/flexboxgrid#227]
```html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
	<style>
		*{
			margin: 0;
			padding: 0;
		}
		header{
			height: 60px;
			background: #6290FF;
			color: #fff;
		}
	</style>
</head>
<body>
	<header>
		<div class="row">
			<div class="col-xs">
				<div class="box">
					<a>logo</a>
				</div>
			</div>
			<div class="col-xs">
				<div class=box>
				</div>
			</div>
		</div>
	</header>
</body>
</html>
```

problem: the html got overflow. check out the screenshot

![screen_shot_2016-12-28_at_5_26_27_pm](https://cloud.githubusercontent.com/assets/538657/21519912/230462b6-cd23-11e6-88b2-859d31acdb9a.png)

**Comment by SuEric** [comment]
How to solve this?? @kristoferjoseph

**Comment by evgenyrodionov** [comment]
Seems like `flexboxgrid` was abandoned by @kristoferjoseph, so I forked project and made [flexboxgrid2](https://github.com/evgenyrodionov/flexboxgrid2).

What is already done:
- added breakpoint `xl` for 1200px and `sm` now pointed to 576px (#232) like Bootstrap v4,
- fixed `.container` class and now it works properly and not causing horizontal scroll (#254),
- cleaned up from messy structure (#249)

flexboxgrid2 right now is alpha5, so if you can test it and fills issues (or PRs!) I'll be very grateful.

**Comment by craigcosmo** [comment]
close issue due to framework no longer maintained. Recommend using bootstrap 4
