### ISSUE TITLE
Internet Explorer <10

### ISSUE THREAD

**Issue by muuvmuuv** [kristoferjoseph/flexboxgrid#230]
IE can not handle `text-align:start/end`.
Could you add a `text-align:left/right` before the `start/end`. So IE can use it.

* Browser: IE 10

**Comment by thetwosents** [comment]
So I have browserstack available if anyone wants to do some major testing with availability of flex box grid on the major browsers to log it out. I love this framework, but yea, not supported.

**Comment by anasanzari** [comment]
is IE fallback css available for flexboxgrid?

**Comment by kristoferjoseph** [comment]
I will not be supporting IE < 10 
Feel free to create a project that overrides these classes and link to it here if need be.

💌
