### ISSUE TITLE
Parsing error- jest

### ISSUE THREAD

**Issue by VladiPeled** [kristoferjoseph/flexboxgrid#247]
### Briefly ( tweet size ) describe your issue and how you discovered it.
While testing with jest, the following problem appears

/home/vladi/git/ReactReduxTestingUsingJestEnzyme/node_modules/flexboxgrid/dist/flexboxgrid.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.container-fluid,
                                                                                             ^
    SyntaxError: Unexpected token .
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (node_modules/react-flexbox-grid/lib/classNames.js:8:20)
      at Object.<anonymous> (node_modules/react-flexbox-grid/lib/components/Row.js:9:19)

### Expected behavior

parsing flexboxgrid.css

### Actual behavior

throwing exception

### Steps to reproduce behavior

react component:
import flexboxgrid 

run test of the component:
npm test

**Comment by kristoferjoseph** [comment]
sounds like a jest issue.
if you can make a reduced test case project i will look at it, but my experience with jest is that it causes more issues than it solves.

**Comment by michaelgmiller** [comment]
Also seeing the issue. Will see if I can come up with a test case tomorrow.

**Comment by michaelgmiller** [comment]
Reduced test case:

[testJest.zip](https://github.com/kristoferjoseph/flexboxgrid/files/1059866/testJest.zip)

Steps to reproduce:
1. Unzip
2. npm install
3. npm test

If you comment out "require('flexboxgrid');" in doh.jsx, everything works.

**Comment by michaelgmiller** [comment]
Between versions flexboxgrid@6.1.1 and flexbox@6.2.0, the error changes from:
    Cannot find module 'flexboxgrid' from 'doh.jsx'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (__tests__/doh.jsx:1:129)

to
    SyntaxError: Unexpected token .

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:321:12)
      at Object.<anonymous> (__tests__/doh.jsx:1:129)

**Comment by michaelgmiller** [comment]
If remove the contents of node_modules/flexboxgrid/dist/flexgrid.css, or replace it with a JS comment, everything works. As soon as I put a CSS rule in that file, everything breaks.

**Comment by michaelgmiller** [comment]
One of my coworkers found a solution:
`jest.mock('flexboxgrid', () => {}, {virtual: true});`
