### ISSUE TITLE
In downloaded archive css has different flexboxgrid.css

### ISSUE THREAD

**Issue by evgenyrodionov** [kristoferjoseph/flexboxgrid#249]
### Briefly ( tweet size ) describe your issue and how you discovered it.
When I click download from http://flexboxgrid.com and then use `flexboxgrid.css` from `/css` directory I have different values. It's very counterintuitive. 

### Expected behavior
In `/css` directory I'll have actual file or linked from `/dist`

Diff: https://www.diffchecker.com/aR2jOtYP

**Comment by n-e-t-t-u-n-o** [comment]
I nearly went all grey just because of that

**Comment by alekseevgeorgy** [comment]
This made so much headache.

**Comment by redelvis** [comment]
I faced same problem few days ago. Pls make Flexboxgrid great again!

**Comment by evgenyrodionov** [comment]
cc @kristoferjoseph

**Comment by evgenyrodionov** [comment]
Seems like `flexboxgrid` was abandoned by @kristoferjoseph, so I forked project and made [flexboxgrid2](https://github.com/evgenyrodionov/flexboxgrid2).

What is already done:
- added breakpoint `xl` for 1200px and `sm` now pointed to 576px (#232) like Bootstrap v4,
- fixed `.container` class and now it works properly and not causing horizontal scroll (#254),
- cleaned up from messy structure (#249)

flexboxgrid2 right now is alpha5, so if you can test it and fills issues (or PRs!) I'll be very grateful.
