### ISSUE TITLE
Native css version with variables

### ISSUE THREAD

**Issue by lukasoppermann** [kristoferjoseph/flexboxgrid#250]
I would love to have a native version with css variables, that can be used without using postcss.

### Expected behavior
I should be able to set css variables to overwrite the current gutter settings.

### Actual behavior
Css variables are not supported in media queries so this would need to be removed/compiled beforehand.

Is there any chance it would make using this much nicer.

**Comment by nolan-mbo** [comment]
Same thing is being asked for in the React wrapper. [Link](https://github.com/roylee0704/react-flexbox-grid/issues/87). Bit of a workaround is mentioned there using webpack.NormalModuleReplacementPlugin.

**Comment by lukasoppermann** [comment]
I actually build my own version https://github.com/nuclei/raster
