### ISSUE TITLE
col-sm-6 breaking in Safari 10

### ISSUE THREAD

**Issue by jimmyadaro** [kristoferjoseph/flexboxgrid#252]
### Briefly ( tweet size ) describe your issue and how you discovered it.

I'm using Chrome (59.0 64 bits) and Safari (10.0.3), and `col-sm-6` breaks the 2-columns system placing one under the other. I solved it replacing `flex-basis: 50%` with `flex-basis: 49.94%`, but you guys may want to check it.

### Expected behavior

One column next the other.

### Actual behavior

One column in top of the other.

### Steps to reproduce behavior

1. Create a row with two `col-sm-6`.
2. Open Safari 10.
3. You may need to resize the window.

* OS: macOS Sierra 10.12.3
* Browser: Safari 10.0.3
* code/fiddle/pen url: –

**Comment by jimmythecoder** [comment]
Tested works fine for me on Safari 10.1.

**Comment by jimmyadaro** [comment]
@jimmythecoder Yep, I was using a clearfix in both rows and columns. My fault.
