### ISSUE TITLE
.row causing horizontal scroll when there's content.

### ISSUE THREAD

**Issue by justinemar** [kristoferjoseph/flexboxgrid#254]
No styles yet added to any of the elements , i also removed my reset.css to check if it's the one causing the issue but no luck.. upon inspecting the page with dev tool and changing or removing .row the horizontal scroll disappears.
```
<body>
	<header class="main-header header-bg">
	<div id="header-texts">
		<h1> Hi, i'm jcan.</h1>
		<h1> I'm a front-end developer </h1>
	</div>
	</header>
	<section id="main-section">
	 <div class="row">
    	<div class="col-xs-12 col-sm-8 col-md-6 col-lg-3">
          <div class="box">responsive (no)</div>
   		</div>
	 </div>
	</section>
</body>

```

trying auto-width gives me the same issue
```
<div class="row">
    <div class="col-xs">
        <div class="box">auto</div>
    </div>
</div>
```
Not tested yet to other browsers only chrome
Chrome: Version 60.0.3112.78 (Official Build) (32-bit)

**Comment by evgenyrodionov** [comment]
Seems like `flexboxgrid` was abandoned by @kristoferjoseph, so I forked project and made [flexboxgrid2](https://github.com/evgenyrodionov/flexboxgrid2).

What is already done:
- added breakpoint `xl` for 1200px and `sm` now pointed to 576px (#232) like Bootstrap v4,
- fixed `.container` class and now it works properly and not causing horizontal scroll (#254),
- cleaned up from messy structure (#249)

flexboxgrid2 right now is alpha5, so if you can test it and fills issues (or PRs!) I'll be very grateful.
