### ISSUE TITLE
Any reason for mixing rem and em in :root properties?

### ISSUE THREAD

**Issue by majman** [kristoferjoseph/flexboxgrid#261]
All the `--screen` properties are set explicitly in `em` units, and the `--container` props get evaluated to `rem`. 

Was there any particular thinking or implications that we should be aware of?

**Comment by kristoferjoseph** [comment]
yes, it's because of a bug in safari. It does not support rem based media queries.
Which is fine, since the biggest issue with ems is how they inherit in a wonky way. I prefer rems because of the way you can manipulate all measure by adjusting the html font-size value.💕
