### ISSUE TITLE
Building flexboxgrid from SCSS

### ISSUE THREAD

**Issue by aldencolerain** [kristoferjoseph/flexboxgrid#270]
I think it might be worth considering building the CSS from SCSS.  I've taken a few minutes to create a SCSS version.  This would let people using SCSS import it and also give CSS builds for people that just want to include it.  Checkout my Gist version here:

https://gist.github.com/aldencolerain/75555567553c5e607a185014644a3ee5

**Comment by Vas-Holvi** [comment]
Would also be great to be able to import it directly from an npm module with eyeglass (check e.g. this https://github.com/modularscale/modularscale-sass/blob/3.x/package.json#L9)

**Comment by Laggii** [comment]
Wtf guys, just use @import and import css from dist...

**Comment by ashwinvandijk** [comment]
@Laggii https://github.com/sass/node-sass/issues/2362

**Comment by kristoferjoseph** [comment]
please use css.
