### ISSUE TITLE
Configure with Angular

### ISSUE THREAD

**Issue by ranouf** [kristoferjoseph/flexboxgrid#273]
Hi,

I followed the instruction here : https://github.com/kristoferjoseph/flexboxgrid to install your npm package to my angular App.
`npm i flexboxgrid --save`

I exepected to have this code working immediately:
```
<div class="row">
  <div class="col-xs">
    <div class="box">auto</div>
    <div class="box">auto</div>
    <div class="box">auto</div>
    <div class="box">auto</div>
    <div class="box">auto</div>
  </div>
</div>
```

But not, so I thougth maybe to add the css file in Angular-cli.json like this:

```
{
...
"apps": [{
        ...
        "styles": [
                ...
                "styles.scss",
                "../node_modules/flexboxgrid/css/flexboxgrid.min.css"
      ],
}]
...
}
```

I rebuilt my angular app just in case. But It s still not working.

Here is my list of packages:

```
"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@aspnet/signalr": "^1.0.0-preview1-update1",
    "@covalent/core": "^1.0.0",
    "angular2-jwt": "^0.2.3",
    "core-js": "^2.5.3",
    "flexboxgrid": "^6.3.1",
    "hammerjs": "^2.0.8",
    "npm": "^5.7.1",
    "rxjs": "^5.5.7",
    "to": "^0.2.9",
    "update": "^0.7.4",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.3",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.9",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.4.7",
    "codelyzer": "^4.2.1",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.0.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
```
Can you help me to make it work? And maybe update the readme for the next one who will need to use you package (if necessary).

Thanks

**Comment by AdamVig** [comment]
@ranouf Did you figure this out?

Assuming you left the folder structure as it was generated by the Angular CLI, your path in the `styles` array should not begin with `..`, because the `.angular-cli.json` file should be in the same directory as the`node_modules` directory.

The path itself should be `node_modules/flexboxgrid/dist/flexboxgrid.min.css`. Note that `css` (from your example) was replaced with `dist`.

Another option is to add the following line to the top of `./src/styles.scss`:
```scss
@import '~flexboxgrid/dist/flexboxgrid.min.css`;
```

The tilde translates to `node_modules`.

**Comment by kristoferjoseph** [comment]
Hey there @ranouf ,
I am not an angular user ( nor do I want to be 😄 ), so I am definitely not the right person to ask how to configure an angular app.

If the above comment solves your issue, would you be willing to make a PR to the README to help others who use a framework that requires extra steps to include a css file?

Thank you kindly
