### ISSUE TITLE
Is Flexbox Grid interchangeable with Bootstrap 4's grid classes?

### ISSUE THREAD

**Issue by stamminator** [kristoferjoseph/flexboxgrid#280]
From what I can tell, the classes in Flexbox Grid look to have the same names and behaviors as Bootstrap 4 defaults. Does this mean that, for an existing site where introducing Bootstrap would be too invasive, we could start out by implementing Flexbox Grid, and then move to Bootstrap 4 later down the road without having to refactor the sections using Flexbox Grid classes?

**Comment by Visual-Notes** [comment]
The equality of the class names of Flexbox Grid and Bootstrap disturbed me immediately when I discovered Flexbox Grid. I don't understand why other names were not chosen for Flexbox Grid, since it is quite possible that both Grid systems are used on one website.

**Comment by stamminator** [comment]
@africanforest If the functionality for those classes is identical, then I think that's actually a strength, not a flaw. Of course, that's the crux of my question: _is_ it interchangeable? If not, then you're right, that could be a real problem for people wanting to implement both.

**Comment by Visual-Notes** [comment]
In the case that the backend of a CMS uses bootstrap, the name equivalence of the class names is a problem if a frontend theme wanted to use Flexbox Grid. I am thinking here of the CMS Concrete5, for example, which currently uses Bootstrap 3 in the backend.

**Comment by stamminator** [comment]
Still shouldn't be a problem, so long as the Flexbox Grid CSS file is referenced after Bootstrap is, so that is has a higher specificity than the Bootstrap classes.

**Comment by kristoferjoseph** [comment]
This was discussed at length. I personally liked the original class names I chose, but many users chimed in saying they wanted them to be the same as boostrap ¯\_(ツ)_/¯
https://github.com/kristoferjoseph/flexboxgrid/pull/24
