### ISSUE TITLE
Repeated code

### ISSUE THREAD

**Issue by syedsimanta03** [kristoferjoseph/flexboxgrid#282]
### Briefly ( tweet size ) describe your issue and how you discovered it.
check the core dev written file/dev version on dist folder
...

### Expected behavior
not repeated code
...

### Actual behavior
so many repeated code like xs and sm all using same property values. xs-offset-6 and sm-offset-6 are taking the same property values. so we can just name it offset-6
...

### Steps to reproduce behavior

just check the code on dist

* OS: win 10
* Browser: chrome
* code/fiddle/pen url: https://github.com/kristoferjoseph/flexboxgrid/blob/master/dist/flexboxgrid.css

**Comment by kristoferjoseph** [comment]
This is very much on purpose.
The `xs-` and `sm-` refer to media queries so you can set different properties for different screen sizes.
