### ISSUE TITLE
How to use with Bootstrap

### ISSUE THREAD

**Issue by abeburnett** [kristoferjoseph/flexboxgrid#29]
Thank you for your work on this project. Your implementation of the Flexbox grid system is fantastic. I am running into minor issues attempting to use it alongside Bootstrap. Any tips? Specifically, I think it's the row class which is conflicting.

**Comment by adamjhickey** [comment]
So to use as a drop-in replacement, include the css after the bootstrap css and all will be fine?

**Comment by inoas** [comment]
I am not a bootstrap fan TBH, especially because people miss-use it and do not use a preprocessor and end up with a lot of class soup.

Anyway as a hint you might be able to select bootstrap components you like and skip the grid components of bootstrap and use these here.
