### ISSUE TITLE
Let's make flexboxgrid more discoverable

### ISSUE THREAD

**Issue by makeitcount** [kristoferjoseph/flexboxgrid#290]
This library is awesome and it needs to be more discover-able. I might not use it right now but when I need in future, I want this to be more discoverable. 

Few steps that I can think of 

1. Tag the repo with labels as bootstrap has  : `css` `css-framework` `bootstrap-alternative` `flexbox`
2. I can't think of anything else as of now. Share your ideas

**Comment by jorisw** [comment]
I'd vote to first improve the documentation. One of the basic requirements, setting gutters, breakpoints and margins, as asked in #241, is unclear.
