### ISSUE TITLE
Is this library even maintained anymore?

### ISSUE THREAD

**Issue by i-break-codes** [kristoferjoseph/flexboxgrid#292]
### Issue
I tried to use the library and have already encountered a ton of issues since I've started using.

1. Grids doesn't work for smaller screen if `.container` is used, I mean, there's no padding around it unlike `container-fluid`
2. No documentation around `.box`, `.box-row`, `.container`, `.container-fluid`

**Comment by bobbui** [comment]
use this instead https://github.com/jgthms/bulma

**Comment by sachbearbeiter** [comment]
Try https://github.com/evgenyrodionov/flexboxgrid2

**Comment by GoodJob** [comment]
I was searching for lightweight CSS Grid and it was strange that these grids are not maintened anymore! Suddenly I have realised why - browsers have implemented grids to the standard functions! 

Here is how to move from flexgridbox/bootstrap to standard CSS Grid:
https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/

Here is what CSS Grid is:
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids
