### ISSUE TITLE
Equal height columns

### ISSUE THREAD

**Issue by Ramblurr** [kristoferjoseph/flexboxgrid#40]
Would love to see a feature to make all the columns in a row equal height.

**Comment by stefanw** [comment]
I'm having trouble making same height columns work with flexboxgrid. Same column heights are also not present in the examples on the website.

Here's why I think it can't work:

- you have to set a `background-color` on the flex items (`.col-*` not `.box`) to have a visible same height column effect.
- you then have to set a margin between columns, otherwise they have no visible distance between each other.
- the applied margin breaks the grid.

Here's a code pen demonstrating the effect: http://codepen.io/anon/pen/azqByz

Am I missing a very obvious solution here? I could use a `border` to fake column distance and keep the grid working, but that seems like a hack.

**Comment by Aybee** [comment]
I don't know why, but for some reasons the COLs are set to display:flex;. That means, that not only the COLs but also the BOXes are flex items. Set the BOXes (flex items) to flex-grow:1;. Now you can work with your red color on the BOXes. First remove your extra margin from the COLs (.row > div).

**Comment by kristoferjoseph** [comment]
@stefanw @Ramblurr I will add the ability to set equal height columns.

**Comment by vyscond** [comment]
Could put the commit for reference? The homepage does not show any specific class to control the height synchronization.

**Comment by adampatarino** [comment]
Did this Enhancement just not get done? @kristoferjoseph is this repo still being maintained?

**Comment by advance512** [comment]
Same question from me. I would love to see a working example.

**Comment by Aybee** [comment]
Here is the example page http://flexboxgrid.com/.

With devtools put in some content into first row. You can replace the row with this html, its the same row with some content.
```html
<div class="row">
  <div class="col-xs-12 col-sm-3 col-md-2 col-lg-1">
    <div class="box-row">
      lorem lorem
    </div>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-8 col-lg-10">
    <div class="box-row">
    </div>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 col-lg-1">
    <div class="box-row">
      lorem
    </div>
  </div>
</div>
```
Now with devtools add some CSS to see that flex items are equal height automaticaly.
```css
[class^="col-"] {
  background-color: rgba(255, 0, 0, .5);
  border: 1px solid;
}
```
What **not** has the same height as the flex items is the content within a flex item. That is right behaviour. If you want to make elements within a flex item stretching to the height of its parent flex item you have to give the content some CSS.
```css
[class^="box-"] {
  height: 100%;
}
```
Some people style the flex items with border, background, shadow etc. but not its content, so they don't need to stretch the flex items inner element (if there is one). If you don't like to style the flex item make sure to put an extra element within an item with height:100%; if you wish equal heights.

ps On the example page the row bottom spacing is not nice set. Its set on the inner content.
```css
.box-row {
  margin-bottom: 1rem;
}
```
its better if its set on the flex items itself.
```css
[class^="col-"] {
  background-color: rgba(255, 0, 0, .5);
  border: 1px solid;
  margin-bottom: 1rem;
}
```

**Comment by advance512** [comment]
Thank you @Aybee, very detailed! I will give it a shot and update.

**Comment by advance512** [comment]
@aybee, I'd say your comment here deserves to be a part of the main docs, or at the very least referenced somewhere in the main Github page.

Here's how it looks:
http://imgur.com/gallery/0MWJF

**Comment by Aybee** [comment]
And thank **you** for the nice pics. :astonished:

**Comment by danielalvez91** [comment]
Thanks @Aybee and @advance512 ! You really helped me with both explanation and pics.

+1 on this should be added to the docs or the website as an example !
