### ISSUE TITLE
Create Stylus version

### ISSUE THREAD

**Issue by kristoferjoseph** [kristoferjoseph/flexboxgrid#43]
Because for some reason people love complicating their build script. ;)

**Comment by kristoferjoseph** [comment]
Closing due to lack of interest

**Comment by kristoferjoseph** [comment]
@tannerlinsley :heart:

**Comment by tannerlinsley** [comment]
Alright!!!! Stylus rules. Have you seen [nzAnimate](http://github.com/nozzle/nzAnimate)? My latest contribution to the stylus and angular world.

**Comment by webeau** [comment]
Yes, please! A stylus build would be perfect!  Thanks!

**Comment by bfil** [comment]
+1

**Comment by mrbormeth** [comment]
+1 :)

Is this project still active?

**Comment by kristoferjoseph** [comment]
@mrbormeth unfollow :p

**Comment by mrbormeth** [comment]
@kristoferjoseph Why? :D

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by farskid** [comment]
@kristoferjoseph: when could you possibly release the support for stylus version?

**Comment by farskid** [comment]
@kristoferjoseph: when could you possibly release the support for stylus version?

**Comment by kristoferjoseph** [comment]
I will not be supporting any preprocessors. The workflow will be CSS only. 7.0 was stalled for way too long over preprocessor issues and I want this project to continue to look forward. Apologies.
