### ISSUE TITLE
6.0.0 breaks all old designs based on 5.0.0

### ISSUE THREAD

**Issue by jeremypbeasley** [kristoferjoseph/flexboxgrid#48]
Using Bower now and when 6.0 was released, it broke everything. I have absolutely not idea what I'm doing wrong but none of the usual classes I've been using for the past 6 months are working.

Example:

http://s.codepen.io/jeremypbeasley/debug/ogzqwd

This just broke 4 websites so any help would be much appreciated. Thanks!

PS. I know I can set bower to only use 5.0 but I still would like to know what the issue is here.

**Comment by kristoferjoseph** [comment]
Fixed in 6.0.1
