### ISSUE TITLE
Unneeded horizontal scroll on all sites

### ISSUE THREAD

**Issue by jeremypbeasley** [kristoferjoseph/flexboxgrid#54]
I'm having a consistent issue on all sites using flexboxgrid where the padding on each .row element is causing a horizontal scroll on the page element. Any idea how I could fix this? Thanks so much!

Example: http://www.goodcorps.com/people

**Comment by Aybee** [comment]
Which browser? No h-scroll on FF 35.0.1.

**Comment by kristoferjoseph** [comment]
@jeremypbeasley Take a look at this closed issue:
https://github.com/kristoferjoseph/flexboxgrid/issues/51

**Comment by jeremypbeasley** [comment]
@kristoferjoseph thanks so much! That makes complete sense.
