### ISSUE TITLE
Nested Grid Sizing

### ISSUE THREAD

**Issue by tannerlinsley** [kristoferjoseph/flexboxgrid#58]
Great work on this!  By far my favorite grid system ever.

When nesting grids like so:
```html
<row>
    <col sm-6>
        <row>
            <col sm-6></col>
            <col sm-6></col>
        </row>
    </col>
    <col sm-6>
    	<row>
            <col sm-4></col>
            <col sm-4></col>
            <col sm-4></col>
        </row>
    </col>
</row>
```
It would be so nice for the sizing classes (xs, sm, etc...) of the smaller rows to be based off of the parent column width.  Have you ever wondered the same?

This way, you can nest grids as deep as you want, and if a parent column ends up being too small, the nested rows (and their columns) would respond appropriately (almost as if each column becomes its own viewport size for nested rows to base themselves off of)

That's hard to explain, :) but this is mostly just a thought, not an issue.

**Comment by kristoferjoseph** [comment]
Intersting. I haven't needed this yet. I'll think on it as I build out more pages and see if I can come up with a elegant solution. Thanks!

**Comment by tannerlinsley** [comment]
@kristoferjoseph I recently integrated flexboxgrid into http://github.com/nozzle/nzGrid.  It's an angular module of layout directives that does exactly what we're talking about. Check it out, let me know what you think.

**Comment by kristoferjoseph** [comment]
Pretty nifty. Will have to dig a bit deeper, but the demo page looks pretty sweet.
