### ISSUE TITLE
Column behaviour at various breakpoints

### ISSUE THREAD

**Issue by Madebym** [kristoferjoseph/flexboxgrid#60]
Just started playing with flexbox grid, and would like to make one thing clearer. For example, if I want one column to stay the same size on all breakpoints, it needs to be prefixed with xs, am I right?

Guess this is the mobile first approach at work. Honestly, never tried designing that way, although I see that it is advocated all over the web. Might try it now with flexbox grid.

**Comment by kristoferjoseph** [comment]
@Madebym You are correct. the `-xs` suffix is used as the default size. All other classes with modifiers ( `-sm`, `-md`, etc. ) are applied to the same element when you want to override the setting for larger viewport sizes.

The way I work is I make a single column layout that reflects the DOM hierarchy ( which ideally matches your content importance ) then add columns in the larger viewport sizes as it makes sense for the design.

**Comment by Madebym** [comment]
@kristoferjoseph Great, thanks for the info and the tip regarding mobile first. 

Still need to wrap my head around the mobile first, I feel like designing that way is cutting off the creativity, but I will most definitely give it a try, perhaps with some clean and simple design for start.

Cheers !!

**Comment by Aybee** [comment]
For all other things you can stay on **mobile last** adjustments. Only thing you should think of with flexboxgrid is that xs is for **xs and up**, sm is for **sm and up** ...
