### ISSUE TITLE
Not sure if it's useful to you, but you can have the npm package name flexgrid

### ISSUE THREAD

**Issue by corysimmons** [kristoferjoseph/flexboxgrid#62]
I see you already have flexboxgrid and that's probably better, but if you're interested, I have flexgrid and can give it to you.

**Comment by kristoferjoseph** [comment]
@corysimmons thank you for the offer. I appreciate it. I think it better to keep it flexboxgrid so as not to confuse. With that said, I was thinking about making a more in depth grid that could be wither `display: table` or `display: flex` based and flexgrid sounds like a super good name for it. Want to collaborate on it?

**Comment by corysimmons** [comment]
Actually I'm not sure I have time to maintain another grid system. I already have one that supports Flexbox as well: https://github.com/corysimmons/lost

I'd be happy to transfer FlexGrid's name over to you when you go to make the new grid though. =)
