### ISSUE TITLE
[SASS] Mark variables as defaults

### ISSUE THREAD

**Issue by gonsfx** [kristoferjoseph/flexboxgrid#63]
I think it would be beneficial to add `!default` as a suffix to all variables so they can easily be overwritten by loading a file prior to the `flexboxgrid.scss` in which the variables to be overwritten are defined.

Example:

```
$column-count: 24;
@import 'node_modules/flexboxgrid/src/sass/flexboxgrid';
```

**Comment by kristoferjoseph** [comment]
That's a great idea.
