### ISSUE TITLE
Column display flex bug

### ISSUE THREAD

**Issue by prostoandrei** [kristoferjoseph/flexboxgrid#64]
%column {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      flex-grow: 0;
      flex-shrink: 0;
      padding-right: $half-gutter-width;
      padding-left: $half-gutter-width;
    }

It's a mistake to set display: flex; here. It will stretch inline-block's. This is semantically and logically incorrect

**Comment by Aybee** [comment]
Related https://github.com/kristoferjoseph/flexboxgrid/issues/61
