### ISSUE TITLE
Compatible columns cause wrapping behavior

### ISSUE THREAD

**Issue by volkanunsal** [kristoferjoseph/flexboxgrid#67]
I have two columns of 8 and 4 units in width. When I use them together inside a row, I expect them to appear side by side, but instead I notice that the last item wraps to the next line. I managed to prevent this by setting `max-width: 66.59%;` from the original `66.666666667%` on the larger column. Not sure why this might be happening. I don't have any padding or margin on the columns –– only the padding inherent in the grid system, and removing that does not solve the problem.

**Comment by Aybee** [comment]
Show a page please.

**Comment by kristoferjoseph** [comment]
Thanks for reporting this. Can you [please fork this codepen](http://codepen.io/dam/pen/rajLmx) and reproduce your issue for me? Thanks

**Comment by volkanunsal** [comment]
Figured out the problem. I am using this alongside bootstrap grid. They largely work well together. The only thing I had to add to my code is the following:

```css
// Override the Bootstrap grid
.row:before, .row:after {
  content: initial;
  display: none;
}
```

**Comment by kristoferjoseph** [comment]
Good to know. You also reminded me that I want to eventually use calc to round to three decimal points in the future.
