### ISSUE TITLE
`display: flex` on flex-items causes unpredictable and undesirable behavior on child elements

### ISSUE THREAD

**Issue by kboucher** [kristoferjoseph/flexboxgrid#68]
Based on my understanding of how flexbox is intended to work, the `display: flex|inline-flex` assignment is intended for the flexbox *container* (not the items themselves.)

The presence of the `display: flex` property on the `col-*` elements results in undesired behavior of child elements. We first encountered issues when `svg` elements in `col-*`'s could NOT be displayed `inline`; we later concluded that all `inline` elements in `col-*`'s were displayed as blocks (again, b/c of the `display: flex` on the `col-*` elements.)

**Comment by kristoferjoseph** [comment]
This was added for nested grid behaviors and layout modifiers. I am open to removing it since this is a more important use case than the nested behavior.

**Comment by kboucher** [comment]
I think that, like in Bootstrap, it will be necessary to add a child `row` to the column for nested grids:

    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12"></div>
            </div>
        </div>
    </div>

**Comment by kboucher** [comment]
Offending CSS declarations have been removed.

**Comment by kristoferjoseph** [comment]
You mean like this:
http://flexboxgrid.com/#nested
