### ISSUE TITLE
Only works for col-xs

### ISSUE THREAD

**Issue by arpowers** [kristoferjoseph/flexboxgrid#71]
Looks like you didn't test responsive for anything other than col-xs? 

On mobile resolutions, the other column sizes don't have padding and are crushed to the width of their content.

**Comment by arpowers** [comment]
Or it looks like the technique is to add multiple classes to columns. In that case, i suggest that the default behavior be as if i added  col-xs-12 to the element, with the flexibility to alter that.

**Comment by kristoferjoseph** [comment]
I want to understand your desired outcome. if you can make a codepen demonstrating the issue I will definitely take a look at it.

I test everything btw and it is working as documented currently ;)
