### ISSUE TITLE
Use package managers to manage vendor files and bump dependencies

### ISSUE THREAD

**Issue by rayshan** [kristoferjoseph/flexboxgrid#77]
Both normalize.css and Modernizr are a bit behind. Would you consider using package managers to mange them and bump them?

I was going to include normalize.css for a project, but since you're already doing so, I'll just rely on you and not introduce a separate dependency :)

**Comment by kristoferjoseph** [comment]
Thanks for bringing this up. I am removing thoes from this project. They were only there for use in the examples and I am moving all examples to another repo. 2.0 will be out shortly with the new structure. Thanks again.

**Comment by rayshan** [comment]
No worries. No dependencies = good. Thanks for your work on this!

**Comment by kristoferjoseph** [comment]
@rayshan My pleasure. Thanks for caring enough to open an issue. Want to make this as useful a project as I can. :)
