### ISSUE TITLE
Sass version bug

### ISSUE THREAD

**Issue by leandroruel** [kristoferjoseph/flexboxgrid#81]
i tried use the sass version, but have a bug on line 34 of the file. 

invalid CSS after "... #{$sm}, #{$md}": expected selector or at-rule, was ", #{$lg} !default;"
        on line 34 of assets/scss/objects/_flexboxgrid.scss

**Comment by kristoferjoseph** [comment]
@leandroruel How are you using this?

**Comment by leandroruel** [comment]
i'm using gulp, with gulp-ruby-sass and gulp-minify-css to compile and compress CSS files. just it.
i've imported flexboxgrid.scss to my main .scss file and when i compile he throws this error, not sure what i did wrong. if i remove just the flexboxgrid.scss from the main scss everything works fine.

**Comment by kristoferjoseph** [comment]
That is an issue with the gulp plugin not the flexboxgrid. This library uses the latest version of sass and all the features used are in the current sass docs. *[This lib supports compilation with node-sass as you can see here](https://github.com/kristoferjoseph/flexboxgrid/blob/7.0/package.json#L10)* It compiles when used with the correct sass compiler version.
