### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by suchy** [kristoferjoseph/flexboxgrid#85]
Hi,
It will be nice to know which browsers are supported. The best way will be to put it on website.

Thanks ;-)

**Comment by kristoferjoseph** [comment]
Good idea. Would you be happy with the standard support badge? I already link to caniuse, if I made that more prominent would it suffice?

**Comment by suchy** [comment]
Now I found the link ;-) Badges will be cool, but better link description will be enough (instead of "flex") ;-)

Btw do you plan any fallbacks?

**Comment by kristoferjoseph** [comment]
OK. Badges it is. I am currently working on a fallback example. I won't be building them into this project but will show how to do it. [Here is a quick and dirty test repo showing the general approach](https://github.com/kristoferjoseph/flextable)

**Comment by NetanelBasal** [comment]
So, what is the Browser support?

**Comment by kristoferjoseph** [comment]
@NetanelBasal Flexboxgrid works in all browsers that support the `flex` display property:
http://caniuse.com/#feat=flexbox

Support section coming to the website in 7.0

**Comment by heyallan** [comment]
> Support section coming to the website in 7.0

Excelent!

Flexbox support is not necessarily the same as flexboxgrid.css support. So I'm happy to see that section on 7.0, it adds clarity :+1:

**Comment by leandroruel** [comment]
Safari 5 (i mean the new IE) don't fucking support Flex property. Safari sucks.

**Comment by joaocunha** [comment]
I find it very important to be specific that even partial support is enough (IE10, IE11 and Android 4.3).
