### ISSUE TITLE
flex-direction: 'column'

### ISSUE THREAD

**Issue by wmertens** [kristoferjoseph/flexboxgrid#91]
Why is there no column wrapper class? That's needed for making a header+flex center+footer page, I think.

**Comment by wmertens** [comment]
Here's how to do "the holy grail" page in flexbox, it needs flex-direction and it needs to be able to change it based on width... http://philipwalton.github.io/solved-by-flexbox/demos/holy-grail/

**Comment by kristoferjoseph** [comment]
This is more of a page layout concern than a grid one. You are recommended to read that article then add flexboxgrid to your holy grail layout.
