### ISSUE TITLE
flex class

### ISSUE THREAD

**Issue by wmertens** [kristoferjoseph/flexboxgrid#92]
would be nice to have a `flex` class or maybe `flex-1` that simply sets `flex: 1`

**Comment by wmertens** [comment]
I now notice that cols have flex-grow set to 1 already, so maybe a flex-0 or no-grow might be handy

**Comment by kristoferjoseph** [comment]
Interesting. I was considering this to be outside the realm of the grid itself. All the grid is doing is supplying the grid elements. What a user does with their own content is up to them. From my understanding you have the control you need over the column and rows you need to do a grid layout. If I were to add the entire flex spec to this grid it would not be a grid anymore. :)
