### ISSUE TITLE
Release date of version 7

### ISSUE THREAD

**Issue by brunowego** [kristoferjoseph/flexboxgrid#94]
Hello great people, you guys have any date release of version 7? Thanks.

**Comment by brunowego** [comment]
Answered here https://github.com/kristoferjoseph/flexboxgrid/pull/80#issuecomment-109360189

**Comment by kristoferjoseph** [comment]
Good question, sorry this release has taken so long. The main reason for the delay is differences in SCSS implementations between compilers. I have already received a lot of "Does not compile with `*-sass` compiler version _blah_" issues on the unreleased 7.0 branch. Looks like a couple of the PRs that landed this weekend fix some of the incompatibilities ( HOORAY FOR OPEN SOURCE!!! ), but I need to do a once over and test everything before releasing.
Thank you for the interest and your PRs! You rock sir.

**Comment by brunowego** [comment]
Thanks @kristoferjoseph :+1:
